import type { Debt, DashboardMetrics, TimelineEvent } from "@/types";

export const mockMetrics: DashboardMetrics = {
  total_em_aberto: 847500,
  total_em_aberto_brl: 4237500,
  recuperado_mes: 125000,
  recuperado_mes_brl: 625000,
  taxa_sucesso: 68.4,
  casos_ativos: 43,
  casos_vencidos: 12,
  variacao_mensal: 12.5,
};

const mockTimeline: TimelineEvent[] = [
  {
    id: "t1",
    divida_id: "d1",
    tipo: "cadastro",
    descricao: "Dívida cadastrada no sistema",
    data: "2024-01-15T10:00:00Z",
    autor: "João Silva",
  },
  {
    id: "t2",
    divida_id: "d1",
    tipo: "contato",
    descricao: "E-mail de notificação enviado ao devedor",
    data: "2024-01-20T09:00:00Z",
    canal: "email",
    autor: "Sistema",
  },
  {
    id: "t3",
    divida_id: "d1",
    tipo: "contato",
    descricao: "WhatsApp enviado: lembrete de pagamento",
    data: "2024-02-01T10:30:00Z",
    canal: "whatsapp",
    autor: "Sistema",
  },
  {
    id: "t4",
    divida_id: "d1",
    tipo: "negociacao",
    descricao: "Devedor solicitou parcelamento em 3x",
    data: "2024-02-10T14:00:00Z",
    autor: "Maria Santos",
  },
  {
    id: "t5",
    divida_id: "d1",
    tipo: "ai_sugestao",
    descricao: "IA sugere oferecer desconto de 15% para fechamento imediato",
    data: "2024-02-12T11:00:00Z",
    autor: "Assistente IA",
  },
];

export const mockDebts: Debt[] = [
  {
    id: "d1",
    credor_id: "c1",
    devedor: {
      id: "dev1",
      nome: "Carlos Mendonça Ltda",
      cpf_cnpj: "12.345.678/0001-90",
      email: "financeiro@carlosmendonca.com.br",
      telefone: "(11) 98765-4321",
      endereco: "Av. Paulista, 1000",
      cidade: "São Paulo",
      estado: "SP",
      cep: "01310-100",
      tipo: "pessoa_juridica",
    },
    descricao: "Fornecimento de equipamentos industriais – Contrato #2024-001",
    valor_original: 45000,
    moeda_original: "USD",
    valor_brl: 225000,
    taxa_cambio: 5.0,
    data_vencimento: "2024-01-10",
    data_cadastro: "2024-01-15",
    status: "em_negociacao",
    regime_cobranca: [
      { id: "rc1", dia: 1, canal: "email", template: "lembrete_amigavel", ativo: true },
      { id: "rc2", dia: 7, canal: "whatsapp", template: "segundo_aviso", ativo: true },
      { id: "rc3", dia: 15, canal: "email", template: "aviso_formal", ativo: true },
      { id: "rc4", dia: 30, canal: "telefone", template: "cobranca_direta", ativo: true },
    ],
    documentos: ["contrato_2024_001.pdf", "nota_fiscal_001.pdf"],
    observacoes: "Cliente antigo, boa relação comercial. Dificuldades financeiras temporárias.",
    historico: mockTimeline,
  },
  {
    id: "d2",
    credor_id: "c1",
    devedor: {
      id: "dev2",
      nome: "Ana Paula Ferreira",
      cpf_cnpj: "987.654.321-00",
      email: "ana.ferreira@email.com",
      telefone: "(21) 97654-3210",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      tipo: "pessoa_fisica",
    },
    descricao: "Consultoria de TI – Projeto de Transformação Digital",
    valor_original: 15000,
    moeda_original: "EUR",
    valor_brl: 88500,
    taxa_cambio: 5.9,
    data_vencimento: "2024-02-28",
    data_cadastro: "2024-02-01",
    status: "vencido",
    regime_cobranca: [
      { id: "rc5", dia: 3, canal: "email", template: "lembrete_amigavel", ativo: true },
      { id: "rc6", dia: 10, canal: "sms", template: "segundo_aviso", ativo: true },
    ],
    documentos: ["proposta_consultoria.pdf"],
    historico: [
      {
        id: "t6",
        divida_id: "d2",
        tipo: "cadastro",
        descricao: "Dívida cadastrada no sistema",
        data: "2024-02-01T09:00:00Z",
        autor: "João Silva",
      },
      {
        id: "t7",
        divida_id: "d2",
        tipo: "vencimento",
        descricao: "Dívida venceu sem pagamento",
        data: "2024-02-28T23:59:00Z",
        autor: "Sistema",
      },
    ],
  },
  {
    id: "d3",
    credor_id: "c1",
    devedor: {
      id: "dev3",
      nome: "Tech Solutions Brasil S.A.",
      cpf_cnpj: "98.765.432/0001-10",
      email: "contas@techsolutions.com.br",
      telefone: "(11) 3456-7890",
      cidade: "Campinas",
      estado: "SP",
      tipo: "pessoa_juridica",
    },
    descricao: "Licença de software anual – Suite Enterprise 2024",
    valor_original: 8500,
    moeda_original: "GBP",
    valor_brl: 54400,
    taxa_cambio: 6.4,
    data_vencimento: "2024-03-15",
    data_cadastro: "2024-03-01",
    status: "pago",
    regime_cobranca: [],
    documentos: ["licenca_software.pdf", "comprovante_pagamento.pdf"],
    historico: [
      {
        id: "t8",
        divida_id: "d3",
        tipo: "cadastro",
        descricao: "Dívida cadastrada no sistema",
        data: "2024-03-01T10:00:00Z",
        autor: "João Silva",
      },
      {
        id: "t9",
        divida_id: "d3",
        tipo: "pagamento",
        descricao: "Pagamento integral recebido via transferência internacional",
        data: "2024-03-10T16:30:00Z",
        valor: 54400,
        autor: "Sistema",
      },
    ],
  },
  {
    id: "d4",
    credor_id: "c1",
    devedor: {
      id: "dev4",
      nome: "Grupo Meridional Comércio",
      cpf_cnpj: "11.222.333/0001-44",
      email: "juridico@grupomeridional.com.br",
      telefone: "(51) 99988-7766",
      cidade: "Porto Alegre",
      estado: "RS",
      tipo: "pessoa_juridica",
    },
    descricao: "Exportação de matéria-prima – Lote #78-B",
    valor_original: 32000,
    moeda_original: "USD",
    valor_brl: 160000,
    taxa_cambio: 5.0,
    data_vencimento: "2024-04-30",
    data_cadastro: "2024-04-01",
    status: "pendente",
    regime_cobranca: [
      { id: "rc7", dia: 5, canal: "email", template: "lembrete_amigavel", ativo: true },
      { id: "rc8", dia: 15, canal: "whatsapp", template: "segundo_aviso", ativo: true },
      { id: "rc9", dia: 30, canal: "carta", template: "aviso_formal", ativo: true },
    ],
    documentos: ["contrato_exportacao.pdf"],
    historico: [
      {
        id: "t10",
        divida_id: "d4",
        tipo: "cadastro",
        descricao: "Dívida cadastrada no sistema",
        data: "2024-04-01T11:00:00Z",
        autor: "João Silva",
      },
    ],
  },
  {
    id: "d5",
    credor_id: "c1",
    devedor: {
      id: "dev5",
      nome: "Roberto Nascimento",
      cpf_cnpj: "123.456.789-09",
      email: "roberto.n@gmail.com",
      telefone: "(85) 98877-6655",
      cidade: "Fortaleza",
      estado: "CE",
      tipo: "pessoa_fisica",
    },
    descricao: "Serviços de design gráfico – Projeto de identidade visual",
    valor_original: 3200,
    moeda_original: "USD",
    valor_brl: 16000,
    taxa_cambio: 5.0,
    data_vencimento: "2024-03-01",
    data_cadastro: "2024-02-15",
    status: "vencido",
    regime_cobranca: [
      { id: "rc10", dia: 1, canal: "email", template: "lembrete_amigavel", ativo: true },
      { id: "rc11", dia: 7, canal: "whatsapp", template: "segundo_aviso", ativo: true },
    ],
    documentos: ["briefing_design.pdf"],
    historico: [
      {
        id: "t11",
        divida_id: "d5",
        tipo: "cadastro",
        descricao: "Dívida cadastrada no sistema",
        data: "2024-02-15T14:00:00Z",
        autor: "João Silva",
      },
      {
        id: "t12",
        divida_id: "d5",
        tipo: "contato",
        descricao: "E-mail de cobrança enviado",
        data: "2024-03-02T09:00:00Z",
        canal: "email",
        autor: "Sistema",
      },
    ],
  },
];
